apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  # local:
  #   push: false
  artifacts:
    - image: mylearniaacr.azurecr.io/learnia/auth
      context: auth-srv
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: mylearniaacr.azurecr.io/learnia/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: mylearniaacr.azurecr.io/learnia/course
      context: course-srv
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: mylearniaacr.azurecr.io/learnia/instructor
      context: instructor-srv
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: mylearniaacr.azurecr.io/learnia/lecture
      context: lecture-srv
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: mylearniaacr.azurecr.io/learnia/purchase
      context: purchase-srv
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .