apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course
  template:
    metadata:
      labels:
        app: course
    spec:
      containers:
        - name: course
          image: mylearniaacr.azurecr.io/learnia/course
          env:
            - name: MONGO_URI
              value: 'mongodb://course-mongo-srv:27017/learnia-course-db'
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef: 
                  name: jwt-secret
                  key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: course-srv
spec:
  selector:
    app: course
  ports:
    - name: course
      protocol: TCP
      port: 3000
      targetPort: 3000